export {
  SyncClient,
  SyncTransport,
  createLiveQuery,
  createSyncClient,
  resolveSocketUrl,
  SerializableError,
} from './sync-client.svelte.js';
export type {
  ConnectionState,
  DynamicSyncClient,
  DynamicSyncClientOptions,
  DynamicSyncContextInput,
  LiveQueryState,
  MaybeGetter,
  MutationReceipt,
  ReadonlySyncTable,
  SerializableErrorConstructor,
  SocketLike,
  SyncAction,
  SyncClientMetric,
  SyncClientOptions,
  SyncErrorInput,
  SyncErrorPayload,
  TableConfig,
  TransportOptions,
} from './sync-client.svelte.js';
